# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  chain-benchmarks:
    dependencies:
    - base
    - chain
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: chain is a new Haskeleton package.
executables:
  chain:
    dependencies:
    - base
    - chain
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: reouno/chain
library:
  dependencies:
  - base
  - cryptohash
  - base16-bytestring
  - bytestring
  - text
  - unix-time
  source-dirs: .
license: MIT
maintainer: Leo Uno
name: chain
synopsis: A new Haskeleton package.
tests:
  chain-test-suite:
    dependencies:
    - base
    - chain
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0'
